### PR TITLE
Update Identity-SummarizeGuestTenantActivity.kql

### PR DESCRIPTION
**Pull request by grbray**
Adding AppDisplayName on the summarize

### CODE REVIEW

**Comment by grbray** [comment]
Feel free to reject, but adding AppDisplayName so you can see what the Guest user is hitting in the tenant, rather than just that a user hit the portal.

**Comment by reprise99** [comment]
Was actually looking at this query a few days ago and thinking it to update it to include applications, is this a better outcome though? This way the apps are tied back to the tenant id

//Summarize the domain names, the count of users and list of users for each guest tenant connecting to your Azure AD tenant
SigninLogs
| where TimeGenerated > ago (30d)
| project
    TimeGenerated,
    UserPrincipalName,
    HomeTenantId,
    AADTenantId,
    Id,
    ResourceTenantId,
    ResourceIdentity,
    UserId,
    AppDisplayName
| where UserId != "00000000-0000-0000-0000-000000000000"
| where ResourceIdentity != ''
| where HomeTenantId != ''
| where HomeTenantId != AADTenantId
| extend GuestDomain = split(UserPrincipalName, '@')[-1]
| summarize
    ['Guest Domain Names']=make_set(GuestDomain),
    ['Distinct User Count']=dcount(UserPrincipalName),
    ['List of Guest Users']=make_set(UserPrincipalName),
    ['List of Applications']=make_set(AppDisplayName),
    ['Count of Applications']=dcount(AppDisplayName)
    by HomeTenantId
| sort by ['Distinct User Count'] desc

**Comment by grbray** [comment]
Maybe?  I thought about that, but then you don't know which users were hitting which app.  There may be a better way to smash them together potentially, but if UserA hits both the portal and M365D, and UserB hits just the Portal, I want to know that delination.  May also be interesting to know if they got hit with a CAP.

Yours:
image

Mine:
image

**Comment by reprise99** [comment]
Yeh I think both work to be honest, could make the case either way, adding the app in one way is definitely useful so lets merge it. You can ultimately still add additional filters after the summarization anyway

**Comment by reprise99** [comment]
merged to main

**Pull request merged**
